# Generated by Django 5.2.1 on 2025-06-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
